name: gwaslab
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.13
  - pip=24.0
  - jupyter==1.0.0
  - pip:
      - gwaslab==3.6.3
      - adjusttext==0.8
      - matplotlib>=3.8,<3.9
      - numpy>=1.21.2,<2
      - pandas>=1.3,!=1.5
      - pysam==0.22.1
      - scikit-allel>=1.3.5
      - scipy>=1.12
      - seaborn>=0.12
      - h5py>=3.10.0
      - pyarrow
      - polars>=1.27.0
      - sumstats-liftover==1.0.0